### ISSUE TITLE
Interface - Activities - Completed Date

### ISSUE THREAD

**Issue by JMurk** [JMurk/Cityworks2014_Testing#14]
Completed Date should only be populated when the Outcome = “CLOSED” or the Activity Type is SR Comment update.  Further, when the Outcome IS CLOSED, it should be using ACTULAFINISHDATE to populate this field.

**Comment by BC89** [comment]
done

**Comment by JMurk** [comment]
Not sure why, but the dates still don't match and the time is way off from system date in CSR

![image](https://cloud.githubusercontent.com/assets/5805454/10194651/f4739840-6757-11e5-847a-00875eba7dbd.png)

**Comment by BC89** [comment]
developer error. done.

**Comment by JMurk** [comment]
Confirmed complete.
